# Generated by Django 5.1.5 on 2025-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('flag_img', models.URLField()),
                ('capital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('population_count', models.BigIntegerField(blank=True, null=True)),
                ('continent_name', models.CharField(max_length=200)),
                ('all_timezone', models.CharField(max_length=100)),
                ('area', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id', 'continent_name'],
            },
        ),
    ]
