# Generated by Django 5.1.5 on 2025-01-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='all_timezone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent_name',
            field=models.CharField(max_length=500),
        ),
    ]
